/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RegistrarUsuario.java
 *
 * Created on 07/01/2013, 08:08:38 AM
 *
 */

package PRESENTACION;

import ENTIDADES.Usuario;
import ENTIDADES.seleccion;
import NEGOCIO.UsuarioBL;
import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.File;
import java.io.InputStreamReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author pc
 */

public class BackupRestoreMovil extends javax.swing.JInternalFrame {
    
    private JPanel contentPane;
    private JFileChooser selection = new JFileChooser();   
    
    private String host="localhost";
    private String puerto="3306";
    private String usuario="root";
    private String contrasena="123456";
    private String basedatos="bdnuevamovil";
    private String formato="custom";
    
    Process proceso;
    ProcessBuilder constructorProceso;

    /** Creates new form RegistrarUsuario */
    public BackupRestoreMovil() {
        initComponents();        
    }

        /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Iconos/bd import.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Iconos/bd import.png"))); // NOI18N
        jButton1.setText("BACKUP DE LA BASE DE DATOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("jfrmRegistrarUsuario");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:   
        //HACER EL BACKUP DE LA BASE DE DATOS     
        
                JOptionPane.showMessageDialog(null, "Colocar la extencion .sql seguida del nombre del backup", "Atención",JOptionPane.INFORMATION_MESSAGE);
                     
                try{
                        JFileChooser fileChooser = new JFileChooser();
                        fileChooser.setApproveButtonText("Guardar Backup de la Base de datos");
                        FileNameExtensionFilter filter =  new FileNameExtensionFilter("Archivos sql", "sql");
                        fileChooser.addChoosableFileFilter(filter);
                        fileChooser.showSaveDialog(null);
                        File fileDB = fileChooser.getSelectedFile();
                        String PATH = fileDB.getAbsolutePath();
 
                        Runtime runtime = Runtime.getRuntime();
 
                        /*backupFile se utiliza para indicarle la ubicacion y nombre del archivo que contendra el backup con la extencion .sql*/
                        //String pathDB = "\"C:\\Program Files (x86)\\MySQL\\MySQL Server 5.1\\bin\\mysqldump.exe\" -uroot -p123456 bdnuevamovil -r "+ PATH;
                        String pathDB = "\"C:\\Archivos de programa\\MySQL\\MySQL Server 5.5\\bin\\mysqldump.exe\" -uroot -p123456 bdnuevamovil -r "+ PATH;
 
                        Process child = runtime.exec(pathDB); 
                        //Process es el que ejecuta el comando para buscar el mysqldump.exe
 
                                        JOptionPane.showMessageDialog(null, "Archivo generado", "Verificar",JOptionPane.INFORMATION_MESSAGE);
                }catch(Exception e){
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Error no se genero el archivo por el siguiente motivo: " + e.getMessage(), "Verificar",JOptionPane.ERROR_MESSAGE);
                }
                
//        String direccion="D:\\backup\\Backup.sql";
//        msBackup(host,puerto,usuario,contrasena,basedatos,formato,direccion);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void msBackup(String host,String puerto,String usuario,String contrasena,String basedatos,String formato,String direccion){
    try{
        constructorProceso=new ProcessBuilder("C:\\Program Files (x86)\\MySQL\\MySQL Server 5.1\\bin\\mysqldump.exe","--verbose","--format",formato,"-f",direccion);
        constructorProceso.environment().put("PGHOST", host);
        constructorProceso.environment().put("PGPORT", puerto);
        constructorProceso.environment().put("PGUSER", usuario);
        constructorProceso.environment().put("PGPASSWORD", contrasena);
        constructorProceso.environment().put("PGDATABASE", basedatos);
        constructorProceso.redirectErrorStream(true);
        proceso=constructorProceso.start();
        
        System.out.print("Terminado backup " + direccion + "\n");
        
    }catch(Exception e){
        System.out.print("Backup \n" + e.getMessage() + "\n");
    }
        
    }
    
   
    public void msRestore(String host,String puerto,String usuario,String contrasena,String basedatos,String formato,String direccion){
    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
