/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfrmInicio.java
 *
 * Created on 07/01/2013, 10:50:54 AM
 */
package PRESENTACION;

import java.awt.Dimension;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;

/**
 *
 * @author pc
 */
public class jfrmInicio extends javax.swing.JFrame {

    /**
     * Creates new form jfrmInicio
     */
    int password;

    public jfrmInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setAutoscrolls(true);

        jMenuBar1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMenuBar1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Iconos/archive.png"))); // NOI18N
        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Iconos/clos.png"))); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Iconos/users.png"))); // NOI18N
        jMenu2.setText("Usuarios");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Iconos/agregarusuario.png"))); // NOI18N
        jMenuItem2.setText("Registro Usuario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);
        jMenuItem2.getAccessibleContext().setAccessibleName("");

        jMenuItem5.setText("Listar Usuarios");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Eliminar Usuario");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Iconos/funciones.png"))); // NOI18N
        jMenu3.setText("Operaciones");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Botones/icononuevo.png"))); // NOI18N
        jMenuItem4.setText("Registrar Certificado");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Iconos/reportes.png"))); // NOI18N
        jMenu4.setMnemonic('R');
        jMenu4.setText("Reportes");

        jMenuItem7.setText("Certificados");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Iconos/manual.png"))); // NOI18N
        jMenu6.setText("Herramientas");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Iconos/calculadora.png"))); // NOI18N
        jMenuItem3.setText("Calculadora");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );

        jDesktopPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        frmInicio inicio = new frmInicio();
        inicio.setLocationRelativeTo(null);
        inicio.setVisible(true);
        dispose();

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
        jfrmInicio.setDefaultLookAndFeelDecorated(false);
    }//GEN-LAST:event_formComponentHidden

    private void jMenuBar1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenuBar1AncestorAdded
        // TODO add your handling code here:

//        if(password==2)
//        {
//            jMenuItem12.setVisible(false);
//            jMenuItem2.setVisible(false);
//            jMenuItem14.setVisible(false);
//        }
//        else
//        {
//            jMenuItem13.setVisible(false);            
//        }        
    }//GEN-LAST:event_jMenuBar1AncestorAdded

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        try {
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("calc");
            p.waitFor();
        } catch (IOException ioe) {
        } catch (InterruptedException ie) {
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        RegistrarUsuario ru = new RegistrarUsuario();

        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = ru.getSize();

        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;

        boolean mostrar = true;
        for (int a = 0; a < jDesktopPane1.getComponentCount(); a++) {
            if (ru.getClass().isInstance(jDesktopPane1.getComponent(a))) {
                mostrar = true;
            } else {
                mostrar = false;
            }
        }
        if (mostrar) {
            jDesktopPane1.add(ru);
            ru.setLocation(width, height);
            ru.show();
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // REGISTRO DE CERTIFICADO
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:

        RegistrarCertificado ru = new RegistrarCertificado();

        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = ru.getSize();

        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;

        boolean mostrar = true;
        for (int a = 0; a < jDesktopPane1.getComponentCount(); a++) {
            if (ru.getClass().isInstance(jDesktopPane1.getComponent(a))) {
                mostrar = true;
            } else {
                mostrar = false;
            }
        }
        if (mostrar) {
            jDesktopPane1.add(ru);
            ru.setLocation(width, height);
            ru.show();
        }

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:}
        ListarUsuarios vv=new ListarUsuarios();

            Dimension desktopSize = jDesktopPane1.getSize();
            Dimension jInternalFrameSize = vv.getSize();

            int width = (desktopSize.width - jInternalFrameSize.width) / 2;
            int height = (desktopSize.height - jInternalFrameSize.height) / 2;

            boolean mostrar=true;
            for (int a=0;a<jDesktopPane1.getComponentCount();a++)
            {
                if(vv.getClass().isInstance(jDesktopPane1.getComponent(a)))
                {
                    mostrar=true;
                }
                 else
                     mostrar=false;
            }
            if(mostrar)
            {
                jDesktopPane1.add(vv);
                vv.setLocation(width, height);
                vv.show();
            }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        EliminarUsuario vv=new EliminarUsuario();

            Dimension desktopSize = jDesktopPane1.getSize();
            Dimension jInternalFrameSize = vv.getSize();

            int width = (desktopSize.width - jInternalFrameSize.width) / 2;
            int height = (desktopSize.height - jInternalFrameSize.height) / 2;

            boolean mostrar=true;
            for (int a=0;a<jDesktopPane1.getComponentCount();a++)
            {
                if(vv.getClass().isInstance(jDesktopPane1.getComponent(a)))
                {
                    mostrar=true;
                }
                 else
                     mostrar=false;
            }
            if(mostrar)
            {
                jDesktopPane1.add(vv);
                vv.setLocation(width, height);
                vv.show();
            }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    //Reporte Certificados
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        ListarCertificados vv=new ListarCertificados();

            Dimension desktopSize = jDesktopPane1.getSize();
            Dimension jInternalFrameSize = vv.getSize();

            int width = (desktopSize.width - jInternalFrameSize.width) / 2;
            int height = (desktopSize.height - jInternalFrameSize.height) / 2;

            boolean mostrar=true;
            for (int a=0;a<jDesktopPane1.getComponentCount();a++)
            {
                if(vv.getClass().isInstance(jDesktopPane1.getComponent(a)))
                {
                    mostrar=true;
                }
                 else
                     mostrar=false;
            }
            if(mostrar)
            {
                jDesktopPane1.add(vv);
                vv.setLocation(width, height);
                vv.show();
            }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //  new jfrmInicio().setVisible(true);
                final jfrmInicio frame = new jfrmInicio();
                frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                frame.setDefaultCloseOperation(jfrmInicio.EXIT_ON_CLOSE);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    public final javax.swing.JMenuItem jMenuItem2 = new javax.swing.JMenuItem();
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables

}
