/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRESENTACION;

import DATOS.Reporte;
import ENTIDADES.TarjetaPropiedad;
import ENTIDADES.seleccion;
import NEGOCIO.*;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KACESE
 */
public class ListarTarjetasPreregistradas extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarCertificados
     */
    public int idCertificado;
    seleccion sel = new seleccion();

    public ListarTarjetasPreregistradas() {
        initComponents();
    }

    DefaultTableModel modeloDatos = new DefaultTableModel();

    public void listarTarjetas() {
        Object listaCertificados[][] = new TarjetaPropiedadBL().listarTarjetas();
        String COLUMNAS[] = {"id_Tarjeta", "Placa", "N° de Tarjeta", "Año de Fabricación", "Marca"};
        modeloDatos = new DefaultTableModel();
        modeloDatos.setDataVector(listaCertificados, COLUMNAS);
        jTable2.setModel(modeloDatos);

        int[] anchos = {10, 70, 10, 10, 0};
        for (int i = 0; i < jTable2.getColumnCount(); i++) {
            jTable2.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Iconos/logo.GIF"))); // NOI18N
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_Tarjeta", "Placa", "N° de Tarjeta", "Año de Fabricación", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("TARJETAS DE PROPIEDAD PREREGISTRADAS");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Botones/select.png"))); // NOI18N
        btnBuscar.setText("SELECCIONAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Botones/buscar.png"))); // NOI18N
        jButton2.setText("BUSCAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        Integer x = idCertificado;
        int idTarjeta = 0;
        if (!x.toString().equals("")) {
            idTarjeta = Integer.parseInt(x.toString());

            try {
                TarjetaPropiedad objTarjetaPropiedad = new TarjetaPropiedadBL().obtenerTarjetaP(idTarjeta);
                
                if (objTarjetaPropiedad.getTipoVehiculo()==4){ // Cualquier Otro tipo de vehículo
                    RegistrarCertificado ad = new RegistrarCertificado();
                    ad.objTarjetaP = objTarjetaPropiedad;
                    ad.intIdTarjeta=idTarjeta;
                    Dimension desktopSize = jfrmInicio.jDesktopPane1.getSize();
                    Dimension jInternalFrameSize = ad.getSize();
                    int width = (desktopSize.width - jInternalFrameSize.width) / 2;
                    int height = (desktopSize.height - jInternalFrameSize.height) / 2;
                    jfrmInicio.jDesktopPane1.add(ad);
                    ad.setLocation(width, height);
                    ad.toFront();                
                    ad.setVisible(true);
                    dispose();
                }else{
                    if (objTarjetaPropiedad.getTipoVehiculo()==2){ //Ómnibus y Camiones
                        
                    }else{ //Semiremolque
                        
                    }
                }

            } catch (NullPointerException ex) {

            }

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un registro para Mostrar el Certificado", "CAMPOS VACÍOS", 0);
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_formAncestorAdded

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        listarTarjetas();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        
        int indX1 = sel.select("id_Tarjeta", jTable2);
        int indX2 = sel.select("Placa", jTable2);
        int indX3 = sel.select("N° de Tarjeta", jTable2);
        int indX4 = sel.select("Año de Fabricación", jTable2);
        int indX5 = sel.select("Marca", jTable2);
        if (indX1 < 0) {
            return;
        }
        idCertificado = Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(), indX1).toString());
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jTable2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
